package:
  name: hello-server
  version: 0.1.0
  description: friendly little webserver
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - ruby

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - ca-certificates-bundle
      - busybox
      - make
      - gcc
      - g++
      - musl-dev
      - ruby
      - ruby-bundler
      - ruby-dev

pipeline:
  - name: Build Ruby application
    runs: |
      EXECDIR="${{targets.destdir}}/usr/bin"
      WEBAPPDIR="${{targets.destdir}}/usr/share/webapps/hello-server"
      mkdir -p "${EXECDIR}" "${WEBAPPDIR}"
      echo "#!/usr/bin/env ruby" > "${EXECDIR}/hello-server"
      echo "Dir.glob('/usr/share/webapps/hello-server/**/lib').each do |p| \$LOAD_PATH << p end" \
        >> "${EXECDIR}/hello-server"
      cat main.rb >> "${EXECDIR}/hello-server"
      chmod +x "${EXECDIR}/hello-server"
      bundler install --path "${WEBAPPDIR}/vendor"
