name: release
inputs:
  variant:
    required: true
  archs:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Populate workspace with variant source only
      shell: bash
      run: |
        shopt -s dotglob && tmp="$(mktemp -d)" && \
          mv ${{ inputs.variant }}/* ${tmp}/ && \
          mv .github ${tmp}/ && \
          rm -rf ./* && mv ${tmp}/* . && \
          echo ".github/" >> .melangeignore && tree -a . && \
          sudo rm -rf /work && sudo mkdir /work

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - uses: chainguard-dev/actions/melange-build@main
      with:
        archs: ${{ inputs.archs }}
        config: melange.yaml
        signing-key-path: /work/melange.rsa
        repository-path: /work/packages
        empty-workspace: false
        sign-with-temporary-key: true

    - name: Create temp copy of /work directory (used in next step)
      shell: bash
      run: |
        rm -rf .apko-automount && cp -r /work .apko-automount

    - uses: chainguard-images/actions/apko-snapshot@main
      with:
        archs: ${{ inputs.archs }}
        config: apko.yaml
        base-tag: ghcr.io/${{ github.repository }}/${{ inputs.variant }}
        keyring-append: /work/melange.rsa.pub
        automount-src: .apko-automount
        automount-dest: /work

    - name: Smoke test
      shell: bash
      run: |
        ref="ghcr.io/${{ github.repository }}/${{ inputs.variant }}"
        docker pull "${ref}"
        COSIGN_EXPERIMENTAL=1 cosign verify "${ref}"
        docker run -d --rm -p 8080:8080 --name smoketest "${ref}"
        trap "docker rm -f smoketest" EXIT
        sleep 5 # Give server a few seconds to come up
        curl -v --max-time 10 http://localhost:8080/ | grep 'Hello World!'

